"""Finding Ollama from inside WSL2 — probe order, the private-address rule, guidance.

The Windows host runs Ollama; WSL2's NAT means 127.0.0.1 is not the host. These tests
pin the order the candidates are tried in and the refusal of anything non-local, with
fake ``/proc/net/route`` and ``/etc/resolv.conf`` contents so they run anywhere.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

import httpx
import pytest

from ops.lib import ollama as ollama_lib
from runs.llm import health as health_mod

# eth0 default route via 172.29.64.1 — little-endian hex, as the kernel prints it
ROUTE = (
    "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\tMTU\tWindow\tIRTT\n"
    "eth0\t00401DAC\t00000000\t0001\t0\t0\t0\t00C0FFFF\t0\t0\t0\n"
    "eth0\t00000000\t01401DAC\t0003\t0\t0\t0\t00000000\t0\t0\t0\n"
)
RESOLV = "# generated by WSL\nnameserver 10.255.255.254\noptions edns0\n"

PROBE = ["http://127.0.0.1:11434", "wsl_gateway", "resolv_nameserver",
         "http://host.docker.internal:11434"]


def test_the_default_gateway_is_parsed_little_endian():
    assert ollama_lib.wsl_default_gateway(ROUTE) == "172.29.64.1"
    assert ollama_lib.wsl_default_gateway("Iface\tDestination\n") is None


def test_the_resolv_nameserver_is_the_first_one():
    assert ollama_lib.resolv_nameserver(RESOLV) == "10.255.255.254"
    assert ollama_lib.resolv_nameserver("search lan\n") is None


def test_candidates_expand_in_the_configured_order():
    assert ollama_lib.expand_candidates(PROBE, route_text=ROUTE,
                                        resolv_text=RESOLV) == [
        "http://127.0.0.1:11434",
        "http://172.29.64.1:11434",
        "http://10.255.255.254:11434",
        "http://host.docker.internal:11434",
    ]


def test_unresolvable_symbolic_entries_simply_drop_out():
    assert ollama_lib.expand_candidates(["wsl_gateway", "resolv_nameserver"],
                                        route_text="", resolv_text="") == []


@pytest.mark.parametrize("url, local", [
    ("http://127.0.0.1:11434", True),
    ("http://localhost:11434", True),
    ("http://172.29.64.1:11434", True),
    ("http://192.168.1.10:11434", True),
    ("http://10.255.255.254:11434", True),
    ("http://169.254.1.1:11434", True),
    ("http://host.docker.internal:11434", True),
    ("http://8.8.8.8:11434", False),
    ("https://ollama.example.com", False),
    ("http://1.1.1.1:11434", False),
])
def test_only_loopback_and_private_addresses_count_as_local(url, local):
    assert ollama_lib.is_local_url(url) is local


def test_a_public_probe_entry_is_never_tried():
    assert ollama_lib.expand_candidates(["http://8.8.8.8:11434"]) == []


def _client(answering: str | None):
    def handler(request: httpx.Request) -> httpx.Response:
        if answering and str(request.url).startswith(answering):
            return httpx.Response(200, json={"version": "0.34.1"})
        raise httpx.ConnectError("connection refused", request=request)

    return httpx.Client(transport=httpx.MockTransport(handler))


def test_detection_keeps_the_first_address_that_answers():
    det = ollama_lib.detect(PROBE, client=_client("http://172.29.64.1:11434"),
                            route_text=ROUTE, resolv_text=RESOLV)
    assert det.ok and det.base_url == "http://172.29.64.1:11434"
    assert det.version == "0.34.1"
    assert [r.url for r in det.results] == ["http://127.0.0.1:11434",
                                            "http://172.29.64.1:11434"]


def test_detection_records_every_failure_when_nothing_answers():
    det = ollama_lib.detect(PROBE, client=_client(None), route_text=ROUTE,
                            resolv_text=RESOLV)
    assert not det.ok and len(det.results) == 4
    assert all(not r.ok for r in det.results)


def test_guidance_names_the_exact_powershell_when_nothing_answers():
    det = ollama_lib.detect(PROBE, client=_client(None), route_text=ROUTE,
                            resolv_text=RESOLV)
    guide = ollama_lib.guidance(det)
    assert guide["reachable"] is False and len(guide["tried"]) == 4
    flat = " ".join(c for option in guide["options"] for c in option["commands"])
    assert "OLLAMA_HOST" in flat and "0.0.0.0" in flat
    assert "networkingMode=mirrored" in flat
    assert "New-NetFirewallRule" in flat


def test_listing_models_maps_the_fields_the_ui_shows():
    def handler(request):
        return httpx.Response(200, json={"models": [
            {"name": "llama3.1:8b", "size": 4661224676,
             "modified_at": "2026-09-01T10:00:00Z",
             "details": {"parameter_size": "8.0B", "quantization_level": "Q4_K_M",
                         "family": "llama"}}]})

    models = ollama_lib.list_models("http://127.0.0.1:11434",
                                    client=httpx.Client(
                                        transport=httpx.MockTransport(handler)))
    assert models == [{"name": "llama3.1:8b", "size": 4661224676,
                       "parameter_size": "8.0B", "quantization": "Q4_K_M",
                       "family": "llama", "modified_at": "2026-09-01T10:00:00Z"}]


def test_pull_streams_progress_frames():
    def handler(request):
        body = (b'{"status":"pulling manifest"}\n'
                b'{"status":"downloading","completed":10,"total":100}\n'
                b'not json\n'
                b'{"status":"success"}\n')
        return httpx.Response(200, content=body)

    frames = list(ollama_lib.pull("http://127.0.0.1:11434", "llama3.1:8b",
                                  client=httpx.Client(
                                      transport=httpx.MockTransport(handler))))
    assert [f["status"] for f in frames] == ["pulling manifest", "downloading", "success"]


# --------------------------------------------------------------------------- caching


class _Provider:
    base_url = "auto"
    probe = PROBE
    timeout_s = 120


def test_the_detected_url_is_cached_for_ten_minutes(kdb):
    now = datetime(2026, 9, 22, 8, 0, tzinfo=UTC)
    url = health_mod.ollama_base_url(_Provider(), kdb=kdb,
                                     client=_client("http://127.0.0.1:11434"),
                                     now=now, route_text=ROUTE, resolv_text=RESOLV)
    assert url == "http://127.0.0.1:11434"
    # a later call inside the window does not probe at all (a dead client proves it)
    assert health_mod.ollama_base_url(
        _Provider(), kdb=kdb, client=_client(None), now=now + timedelta(minutes=5),
        route_text=ROUTE, resolv_text=RESOLV) == "http://127.0.0.1:11434"
    # once the window lapses it probes again and finds nothing
    assert health_mod.ollama_base_url(
        _Provider(), kdb=kdb, client=_client(None), now=now + timedelta(minutes=11),
        route_text=ROUTE, resolv_text=RESOLV) is None


def test_an_explicit_public_base_url_is_refused(kdb):
    class Public(_Provider):
        base_url = "http://ollama.example.com:11434"

    with pytest.raises(ollama_lib.OllamaError, match="not a loopback"):
        health_mod.ollama_base_url(Public(), kdb=kdb)


def test_an_explicit_private_base_url_skips_detection(kdb):
    class Pinned(_Provider):
        base_url = "http://192.168.1.50:11434/"

    assert health_mod.ollama_base_url(Pinned(), kdb=kdb) == "http://192.168.1.50:11434"
