"""The local model, as one read-only line — because the operator must never type a URL.

Everything needed to run a local model already exists: ``ops.lib.ollama`` probes four
candidate endpoints (WSL2's NAT network means ``127.0.0.1`` inside WSL is *not* the
Windows host, so the default gateway and ``host.docker.internal`` are tried too),
``runs.llm.health`` caches the winner in ``ops_state`` for ten minutes, and the pull API
streams progress. What was missing is that all of it was wired to *hand-configuration
fields* — a base URL box and a model box on the AI & Models page — which is exactly the
thing an operator running a paper-trading week should never have to fill in.

So this module answers one question with one sentence:

    local model: connected, llama3.1:8b, 41 tok/s
    local model: unreachable — Ollama is not listening where WSL can see it  ⟨one command⟩
    local model: pulling llama3.1:8b (37%)

and it does the work behind the sentence itself:

* **detect** — the cached-or-probed base URL, never a configured one from the UI;
* **choose** — the model id is whatever ``models.yaml`` already routes local tasks to
  (the alias of the first ``ollama``-provider entry), not a field;
* **pull** — when that model is missing, one background pull is submitted through the
  console's own job runner and the line becomes a progress line until it lands;
* **measure** — tok/s comes from a tiny ``/api/generate`` (``num_predict`` 8) run off the
  request thread and cached for ten minutes, so the line is never a guess and the page
  never waits on a model loading.

Nothing here writes config, and nothing here returns anything an operator has to act on
except, when the endpoint is unreachable, the **one** PowerShell command that fixes it.
"""

from __future__ import annotations

import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

__all__ = [
    "FIX_COMMAND",
    "LocalModelStatus",
    "clear_cache",
    "status",
]

#: How long a throughput measurement is trusted. A model does not get faster in a minute,
#: and re-measuring on every poll would keep an 8B model resident for no reason.
THROUGHPUT_TTL_S = 600.0
#: Bound on the measurement itself: a cold model can take a while to load, and a page
#: poll must never wait on it (the measurement runs in its own thread anyway).
THROUGHPUT_TIMEOUT_S = 120.0
#: Tokens generated by the probe. Enough for a stable rate, small enough to be free.
THROUGHPUT_TOKENS = 8

#: The single command that fixes the usual WSL2 failure: Ollama on Windows binds
#: 127.0.0.1, which inside WSL's NAT network is not the host. Binding 0.0.0.0 and
#: restarting it is the whole fix; the firewall rule is only needed if one blocks it.
FIX_COMMAND = (
    '[Environment]::SetEnvironmentVariable("OLLAMA_HOST","0.0.0.0","User"); '
    "Get-Process ollama* | Stop-Process -Force; "
    'Start-Process "$env:LOCALAPPDATA\\Programs\\Ollama\\ollama app.exe"'
)
FIX_SHELL = "PowerShell (Windows, not WSL)"


@dataclass(frozen=True)
class LocalModelStatus:
    """One line plus the facts behind it. No field here is editable."""

    state: str = "unknown"        # connected | pulling | unreachable | missing | disabled
    line: str = ""
    model: str | None = None
    base_url: str | None = None
    version: str | None = None
    tok_per_s: float | None = None
    reason: str | None = None
    fix_command: str | None = None
    fix_shell: str | None = None
    pull: dict[str, Any] | None = None
    tried: list[str] | None = None

    def as_dict(self) -> dict[str, Any]:
        return {
            "state": self.state,
            "line": self.line,
            "model": self.model,
            "base_url": self.base_url,
            "version": self.version,
            "tok_per_s": self.tok_per_s,
            "reason": self.reason,
            "fix_command": self.fix_command,
            "fix_shell": self.fix_shell,
            "pull": self.pull,
            "tried": list(self.tried or []),
            "configurable": False,
        }


# --------------------------------------------------------------------------- caches

_lock = threading.Lock()
#: ``(base_url, model) -> (tok_s, measured_at_monotonic)``
_throughput: dict[tuple[str, str], tuple[float, float]] = {}
#: ``(base_url, model) -> job id`` for the auto-pull, so one is never submitted twice.
_pulls: dict[tuple[str, str], str] = {}
_measuring: set[tuple[str, str]] = set()


def clear_cache() -> None:
    """Drop every memo. Tests call it; nothing in the app does."""
    with _lock:
        _throughput.clear()
        _pulls.clear()
        _measuring.clear()


# --------------------------------------------------------------------------- the answer


def local_model_id(models_cfg: Any) -> str | None:
    """The model the routing already uses locally — never something the UI picked.

    The first declared alias whose provider is ``ollama``. ``models.yaml`` has exactly one
    today (``local_small``); if a second is added, the first in declaration order is the
    one the chains fall back to, so it is the one whose readiness matters.
    """
    for entry in (getattr(models_cfg, "models", None) or {}).values():
        if entry is not None and getattr(entry, "provider", None) == "ollama":
            model = getattr(entry, "id", None)
            if model:
                return str(model)
    return None


def status(
    models_cfg: Any,
    *,
    knowledge: Path | None = None,
    client: Any = None,
    jobs: Any = None,
    actor: str = "console",
    measure: bool = True,
    now: float | None = None,
) -> dict[str, Any]:
    """The whole local-model story, resolved server-side. Never raises."""
    provider_cfg = (getattr(models_cfg, "providers", None) or {}).get("ollama")
    if provider_cfg is None or not getattr(provider_cfg, "enabled", False):
        return LocalModelStatus(
            state="disabled",
            line="local model: off (no local provider is enabled)",
            reason="providers.ollama.enabled is false in models.yaml",
        ).as_dict()

    model = local_model_id(models_cfg)
    base_url, tried = _detect(provider_cfg, knowledge=knowledge, client=client)
    if not base_url:
        return LocalModelStatus(
            state="unreachable", model=model, tried=tried,
            line="local model: unreachable — Ollama is not listening where WSL can see it",
            reason=(
                "Ollama runs on Windows and binds 127.0.0.1, which inside WSL2's NAT "
                "network is not the host. Nothing here can reach it until it listens on "
                "all interfaces."
            ),
            fix_command=FIX_COMMAND, fix_shell=FIX_SHELL,
        ).as_dict()

    version, names = _inventory(base_url, client=client)
    if model is None:
        return LocalModelStatus(
            state="connected", base_url=base_url, version=version,
            line=f"local model: connected at {base_url}, no local model is routed to",
            reason="no models.yaml alias declares provider: ollama",
        ).as_dict()

    if not _has(model, names):
        pull = _ensure_pull(base_url, model, jobs=jobs, actor=actor)
        if pull is None:
            return LocalModelStatus(
                state="missing", model=model, base_url=base_url, version=version,
                line=f"local model: {model} is not downloaded yet",
                reason="the automatic pull could not be started; it will retry",
            ).as_dict()
        pct = int(round(float(pull.get("progress") or 0.0) * 100))
        return LocalModelStatus(
            state="pulling", model=model, base_url=base_url, version=version, pull=pull,
            line=f"local model: downloading {model} ({pct}%) — nothing for you to do",
        ).as_dict()

    tok_s = _throughput_for(base_url, model, client=client, measure=measure, now=now)
    rate = f", {tok_s:.0f} tok/s" if tok_s else ""
    return LocalModelStatus(
        state="connected", model=model, base_url=base_url, version=version,
        tok_per_s=round(tok_s, 1) if tok_s else None,
        line=f"local model: connected, {model}{rate}",
    ).as_dict()


# --------------------------------------------------------------------------- steps


def _detect(provider_cfg: Any, *, knowledge: Path | None,
            client: Any) -> tuple[str | None, list[str]]:
    """The reachable base URL, from the ten-minute cache or a fresh probe."""
    from ops.lib import ollama as ollama_lib
    from runs.llm import health as health_mod

    tried = ollama_lib.expand_candidates(
        list(getattr(provider_cfg, "probe", None) or ollama_lib.default_probe()))
    try:
        if knowledge is not None and Path(knowledge).exists():
            from ops import db

            # Writable on purpose: a successful probe is cached in ``ops_state`` for ten
            # minutes, which is what stops every page poll re-probing four addresses.
            with db.opened(Path(knowledge)) as conn:
                return health_mod.ollama_base_url(
                    provider_cfg, kdb=conn, client=client), tried
        return health_mod.ollama_base_url(provider_cfg, kdb=None, client=client), tried
    except Exception:  # noqa: BLE001 - an unreachable daemon is a state, not an error
        return None, tried


def _inventory(base_url: str, *, client: Any) -> tuple[str | None, list[str]]:
    from ops.lib import ollama as ollama_lib

    version = ollama_lib.probe_url(base_url, client=client).version
    try:
        models = ollama_lib.list_models(base_url, client=client)
    except Exception:  # noqa: BLE001
        return version, []
    return version, [str(m.get("name") or "") for m in models if m.get("name")]


def _has(model: str, names: list[str]) -> bool:
    """``llama3.1:8b`` matches ``llama3.1:8b``; a bare name matches ``name:latest``."""
    wanted = model.strip()
    if wanted in names:
        return True
    if ":" not in wanted:
        return f"{wanted}:latest" in names
    return False


def _ensure_pull(base_url: str, model: str, *, jobs: Any,
                 actor: str) -> dict[str, Any] | None:
    """Submit at most one background pull for this endpoint+model, and report it."""
    if jobs is None:
        return None
    key = (base_url, model)
    with _lock:
        existing = _pulls.get(key)
    if existing:
        run = jobs.get(existing)
        if run is not None and not run.terminal:
            return {"job_id": run.id, "progress": run.progress, "message": run.message}
        with _lock:
            _pulls.pop(key, None)

    from console.services.jobs import JobSpec
    from ops.lib import ollama as ollama_lib

    name = f"ollama.pull:{model}"

    def pull(progress: Any) -> dict[str, Any]:
        last: dict[str, Any] = {}
        for frame in ollama_lib.pull(base_url, model):
            last = frame
            total, done = frame.get("total"), frame.get("completed")
            if total:
                progress(min(float(done or 0) / float(total), 1.0),
                         str(frame.get("status", "")))
        return {"model": model, "status": last.get("status", "done")}

    try:
        jobs.register(JobSpec(name=name, fn=pull,
                              description=f"pull {model} into the local Ollama"))
        run = jobs.submit(name, actor=actor, args={"model": model},
                          labels={"kind": "local_model"})
    except Exception:  # noqa: BLE001 - a busy runner is "not pulling yet", not a 500
        return None
    with _lock:
        _pulls[key] = run.id
    return {"job_id": run.id, "progress": run.progress, "message": run.message}


def _throughput_for(base_url: str, model: str, *, client: Any, measure: bool,
                    now: float | None) -> float | None:
    """The cached tok/s, kicking off a measurement in the background when it is stale."""
    key = (base_url, model)
    clock = now if now is not None else time.monotonic()
    with _lock:
        cached = _throughput.get(key)
        if cached is not None and clock - cached[1] < THROUGHPUT_TTL_S:
            return cached[0]
        if not measure or key in _measuring:
            return cached[0] if cached else None
        _measuring.add(key)
    thread = threading.Thread(target=_measure, args=(base_url, model, client),
                             name=f"ollama-tok-s-{model}", daemon=True)
    thread.start()
    return cached[0] if cached else None


def _measure(base_url: str, model: str, client: Any) -> None:
    """One tiny generate; Ollama reports ``eval_count`` and ``eval_duration`` itself."""
    key = (base_url, model)
    try:
        rate = measure_throughput(base_url, model, client=client)
        if rate:
            with _lock:
                _throughput[key] = (rate, time.monotonic())
    finally:
        with _lock:
            _measuring.discard(key)


def measure_throughput(base_url: str, model: str, *, client: Any = None,
                       timeout_s: float = THROUGHPUT_TIMEOUT_S) -> float | None:
    """Generation speed in tokens/second, or ``None``. Never raises."""
    http, owned = client, False
    if http is None:
        import httpx

        http, owned = httpx.Client(timeout=timeout_s), True
    try:
        resp = http.post(
            f"{base_url.rstrip('/')}/api/generate",
            json={"model": model, "prompt": "ping", "stream": False,
                  "options": {"num_predict": THROUGHPUT_TOKENS, "temperature": 0}},
            timeout=timeout_s,
        )
        payload = resp.json() or {}
    except Exception:  # noqa: BLE001 - a slow or absent daemon just means "no number"
        return None
    finally:
        if owned:
            try:
                http.close()
            except Exception:  # noqa: BLE001 # pragma: no cover
                pass
    count = payload.get("eval_count")
    nanos = payload.get("eval_duration")
    try:
        if not count or not nanos:
            return None
        return float(count) / (float(nanos) / 1e9)
    except (TypeError, ValueError, ZeroDivisionError):
        return None
